# Generated by Django 5.0.6 on 2026-06-01 19:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato_nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('historico_atrasos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFornecedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(db_index=True, max_length=18)),
                ('contato_nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('historico_atrasos', models.PositiveIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fornecedor',
                'verbose_name_plural': 'historical fornecedors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRastreamento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estagio_atual', models.CharField(choices=[('COMPRA_EFETUADA', 'Compra Efetuada'), ('NF_EMITIDA', 'NF Emitida'), ('SEPARACAO', 'Em Separação'), ('COLETADO', 'Coletado / Embarcado'), ('TRANSPORTE', 'Em Transporte'), ('ENTREGUE', 'Entregue')], default='COMPRA_EFETUADA', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('previsao_entrega', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compras.pedidocompra')),
            ],
            options={
                'verbose_name': 'historical rastreamento',
                'verbose_name_plural': 'historical rastreamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Rastreamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio_atual', models.CharField(choices=[('COMPRA_EFETUADA', 'Compra Efetuada'), ('NF_EMITIDA', 'NF Emitida'), ('SEPARACAO', 'Em Separação'), ('COLETADO', 'Coletado / Embarcado'), ('TRANSPORTE', 'Em Transporte'), ('ENTREGUE', 'Entregue')], default='COMPRA_EFETUADA', max_length=20)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('previsao_entrega', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rastreamento', to='compras.pedidocompra')),
            ],
        ),
    ]
