# Generated by Django 5.0.6 on 2026-06-01 19:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prazo_entrega_dias', models.PositiveIntegerField()),
                ('condicao_pagamento', models.CharField(max_length=100)),
                ('vencedora', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAprovacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('data', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical aprovacao',
                'verbose_name_plural': 'historical aprovacaos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPedidoCompra',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal (24h)'), ('ALTA', 'Alta (8h)'), ('EMERGENCIAL', 'Emergencial (2h)')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('CRIADO', 'Criado pelo Almoxarife'), ('COTACAO', 'Em Cotação'), ('APROVACAO', 'Aguardando Aprovação'), ('REVISAO', 'Revisão Solicitada'), ('COMPRADO', 'Compra Efetuada'), ('TRANSITO', 'Em Transporte'), ('ENTREGUE', 'Entregue')], default='CRIADO', max_length=15)),
                ('justificativa', models.TextField()),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('sla_vencimento', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical pedido compra',
                'verbose_name_plural': 'historical pedido compras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_erp', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade', models.CharField(max_length=10)),
                ('maquina_aplicacao', models.CharField(blank=True, max_length=100)),
                ('prazo_desejado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('prioridade', models.CharField(choices=[('NORMAL', 'Normal (24h)'), ('ALTA', 'Alta (8h)'), ('EMERGENCIAL', 'Emergencial (2h)')], default='NORMAL', max_length=15)),
                ('status', models.CharField(choices=[('CRIADO', 'Criado pelo Almoxarife'), ('COTACAO', 'Em Cotação'), ('APROVACAO', 'Aguardando Aprovação'), ('REVISAO', 'Revisão Solicitada'), ('COMPRADO', 'Compra Efetuada'), ('TRANSITO', 'Em Transporte'), ('ENTREGUE', 'Entregue')], default='CRIADO', max_length=15)),
                ('justificativa', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('sla_vencimento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('tipo', models.CharField(choices=[('PDF', 'Documento PDF'), ('IMG', 'Imagem'), ('XLS', 'Planilha')], max_length=3)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
